runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wishlist.wsgi

runtime_config:
  python_version: 3

env_variables:
  WISHLIST_DB_PW: bf7d2b7377cad86791ff3733f710a2a096351cc7

beta_settings:
  cloud_sql_instances: wishlist-projected-27032018:us-central1:wishlist-travel-db-001
